version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/examplanner?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examplanner
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
